# Generated by Django 5.1.3 on 2024-11-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
